server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.50.43:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.bolingcavalry.simple.entity

#showSql
logging:
  level:
    com:
      bolingcavalry:
        simple:
          mapper: debug
